### PR TITLE
Test iostream include

### PR DESCRIPTION
**Pull request by renefritze**
This is a merge of @tristan0x's #12 and #11 so we can run tests on the result. 

The test from the sdist tarball build [went through](https://github.com/ssciwr/clang-tidy-wheel/runs/7356170146?check_suite_focus=true). The [mac one didn't](https://github.com/ssciwr/clang-tidy-wheel/runs/7356165505?check_suite_focus=true)

### CODE REVIEW

**Comment by tristan0x** [comment]
I have already encountered the issue:

```
error: 'iostream' file not found [clang-diagnostic-error]
  #include <iostream>
           ^~~~~~~~~~`
```

It means clang-tidy is not able to find the libstdc++ on the host. Installing a C++ compiler may fix the issue.

**Comment by renefritze** [comment]
Right, but isn't that what should be solved by #11, which is included in this PR?

**Comment by tristan0x** [comment]
> Right, but isn't that what should be solved by #11, which is included in this PR?

#11 provides [builtin includes](https://clang.llvm.org/docs/LibTooling.html#builtin-includes), which is different than the stdlibc++. The link suggests using `-v` to get the search paths. I will try to reproduce the issue on Mac OS on Monday.

**Comment by renefritze** [comment]
My use case for the tidy wheel actually is a (linux) container with no compiler setup, so generally I'd say that no compiler should be necessary. But practically I'd be happy to just install xcode in the tests for now and maybe add a note to the readme.

**Comment by renefritze** [comment]
[Triggered build with verbose output](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/2695508626)

**Comment by renefritze** [comment]
> I confirm it is the absence of XCode on the MacOS builder (or the tunability to find it) that makes `clang-tidy` fails.

I've had a look at the list of [installed versions](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) for the macos runners. So while there's a default, it does not seem to get picked up, right? OTOH there's also brew-installed gccs and llvms in the machine.

**Comment by tristan0x** [comment]
> [Triggered build with verbose output](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/2695508626)

Thank you for merging the debug code. We can now clearly see that XCode is not found. `xcode-select` should maybe be called somewhere, or the PATH updated to make brew installation visible?

**Comment by tristan0x** [comment]
> [CI: set SDKROOT on macOS builder](https://github.com/ssciwr/clang-tidy-wheel/pull/13/commits/1fd7d8f658b5e0087f800f4ed9cd003e416a7cba)

pipeline running [here](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/2709904354) 🤞

**Comment by renefritze** [comment]
Yeah, no worries. I'm happy to try that, since I also have no insight. Not even a MacOS user.

**Comment by renefritze** [comment]
I dropped 38c6ee3 from the branch and new [pipeline is running](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/2710615927)

**Comment by tristan0x** [comment]
I have no idea at the moment. I am good with your plan, I am not even sure (3) is necessary as it works on my 2 macOS environments but no strong opinion about that.
Thank you

**Comment by renefritze** [comment]
The other platforms' tests worked out. Via the actions summary I learned that the macOS image we're using is being discontinued. So I'm going to try the tests on the newest macOS 12 image, without the xfailing before merging this PR. 
@tristan0x are your working mac environments also macOS 12 already?

**Comment by tristan0x** [comment]
It is worth trying the new setup indeed. Yes I am using Monterey with both
Intel and Silicon chips

**Comment by renefritze** [comment]
Pipeline with all-newest base images and xfailing dropped is [now running](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/2730100891)

**Comment by renefritze** [comment]
That failed early since I also add the qemu build in the branch, [new pipeline](https://github.com/ssciwr/clang-tidy-wheel/runs/7497777489?check_suite_focus=true)

**Comment by renefritze** [comment]
Good news, updating the MacOS image did indeed get rid of the environment problem. 
I'm now running a full test build with all QEMU archs too.

**Comment by renefritze** [comment]
The QEMU jobs seem to have their own problem, so I'm goiung to split the enabling into a separate PR, merge this and then release clang-tidy 13.

**Comment by renefritze** [comment]
I've released tidy 13 for you @tristan0x since this whole setup will take longer still to properly fix and I do not have many cycles to spare atm.

**Comment by renefritze** [comment]
Did the upload manually now
https://pypi.org/project/clang-tidy/13.0.1.1/

**Comment by tristan0x** [comment]
Thank you very much @renefritze

**Pull request merged**
